name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
      - name: Install mdBook
        run: cargo install --git https://github.com/Ruin0x11/mdBook.git --branch localization mdbook

      - name: Build
        run: mdbook build && cp ci/index.html book/ && touch book/.nojekyll && sed -i 's#\.\./\.\./en#../en#' book/zh/*.html

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
